apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-with-argocd-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-with-argocd-deployment
    spec:
      containers:
      - name: app-with-argocd-container
        image: zza1541/app-with-argocd:e43df8dabeacc7ac80342c4336b1be1442bce401
        ports:
          - protocol: TCP
            containerPort: 8080